#' @importFrom dplyr bind_cols
#' @importFrom purrr map2
#' @importFrom purrr safely
#' @importFrom purrr compact
#' @importFrom data.table rbindlist
#' @importFrom purrr imap
#' @importFrom stats median
#' @importFrom data.table data.table
#' @importFrom data.table as.data.table
#' @importFrom data.table dcast
#' @importFrom purrr map
#' @importFrom furrr future_map
#' @importFrom furrr furrr_options
#' @importFrom stats spec.ar
#' @importFrom stats aggregate
#' @importFrom stats ts
#' @importFrom dplyr lag
#' @importFrom dplyr mutate
#' @importFrom tidyr pivot_wider
#' @importFrom dplyr across
#' @importFrom dplyr arrange
#' @importFrom dplyr select
#' @importFrom dplyr left_join
#' @importFrom dplyr group_by
#' @importFrom dplyr summarise
#' @importFrom dplyr ungroup
#' @importFrom dplyr rename
#' @importFrom stats na.omit
#' @importFrom stats rexp
#' @importFrom stats rbinom
#' @importFrom purrr map_dfr
#' @importFrom stats runif
#' @importFrom Rcpp loadModule
NULL
