# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_rows_cpp <- function(x, size, repl = FALSE) {
    .Call('_treecoding_sample_rows_cpp', PACKAGE = 'treecoding', x, size, repl)
}

test_set_diff <- function(x, y) {
    .Call('_treecoding_test_set_diff', PACKAGE = 'treecoding', x, y)
}

debug_tree <- function(num_cols, cat_cols, max_depth = 5L, min_nodesz = 30L) {
    invisible(.Call('_treecoding_debug_tree', PACKAGE = 'treecoding', num_cols, cat_cols, max_depth, min_nodesz))
}

