# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

debug3 <- function(X, col, comp) {
    .Call('_treecoding_debug3', PACKAGE = 'treecoding', X, col, comp)
}

debug4 <- function(X, col, matches) {
    .Call('_treecoding_debug4', PACKAGE = 'treecoding', X, col, matches)
}

debug5 <- function(X, Y) {
    .Call('_treecoding_debug5', PACKAGE = 'treecoding', X, Y)
}

smpl <- function(size) {
    .Call('_treecoding_smpl', PACKAGE = 'treecoding', size)
}

sample_debug <- function(a = 0.3, b = 2.8, size = 100L) {
    .Call('_treecoding_sample_debug', PACKAGE = 'treecoding', a, b, size)
}

shuffler <- function(size = 15L) {
    invisible(.Call('_treecoding_shuffler', PACKAGE = 'treecoding', size))
}

