# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tree <- function(num_cols, cat_cols, max_depth = 5L, min_nodesz = 30L) {
    invisible(.Call('_treecoding_tree', PACKAGE = 'treecoding', num_cols, cat_cols, max_depth, min_nodesz))
}

